name: Publish Maven Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: github

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages
        run: |
          REPO="github::default::https://maven.pkg.github.com/${{github.repository}}"
          mvn -B deploy -DaltReleaseDeploymentRepository="${REPO}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}